# ---------------------------------
# Settings for the baseline method.
#
# author: Konstantinos Drossos
# affiliation: Tampere University
# ---------------------------------
model: !include model_baseline_dcase.yaml
# ----------------------
workflow:
  do_training: True
  do_evaluation: False
# ----------------------
data:
  files: !include files.yaml
  input_field_name: 'features'
  output_field_name: 'words_ind'
  load_into_memory: No
  batch_size: 16
  shuffle: Yes
  num_workers: 6
  drop_last: Yes
  eos_token: '<eos>'
# ----------------------
training:
  nb_epochs: 1000
  patience: 100
  loss_thr: !!float 1e-4
  optimizer:
    lr: !!float 1e-4
  grad_norm:
    value: !!float 1.
    norm: 2
  force_cpu: No
  text_output_every_nb_epochs: !!int 10
  nb_examples_to_sample: 100
# ----------------------
evaluation:
  model_dir: 'last_models'
  model_name: 'model_baseline_dcase.pt'
# ----------------------
logging:
  root_dir: 'outputs'
  logger_dir: 'logging'
  caption_logger_file: 'captions_baseline_dcase.txt'
# EOF
